// ============================================================
// The Cognitive Activity Engine's game registry — the single source of
// truth for every game in Sahaaya. ElderlyActivities.tsx, the caregiver
// analytics screens, and the recommendation engine all read from this list
// instead of each hand-maintaining their own copy of "what games exist."
// ============================================================

import type { GameDefinition } from './types';

import MemoryMatchGame from '../pages/Elderly/Activities/games/MemoryMatchGame';
import ObjectRecognitionGame from '../pages/Elderly/Activities/games/ObjectRecognitionGame';
import AttentionGame from '../pages/Elderly/Activities/games/AttentionGame';
import PatternGame from '../pages/Elderly/Activities/games/PatternGame';
import RoutineRecallGame from '../pages/Elderly/Activities/games/RoutineRecallGame';
import FamilyFacesGame from '../pages/Elderly/Activities/games/FamilyFacesGame';
import ColorFocusGame from '../pages/Elderly/Activities/games/ColorFocusGame';
import QuickResponseGame from '../pages/Elderly/Activities/games/QuickResponseGame';
import NumberFocusGame from '../pages/Elderly/Activities/games/NumberFocusGame';
import BlockMemoryGame from '../pages/Elderly/Activities/games/BlockMemoryGame';
import DualMemoryGame from '../pages/Elderly/Activities/games/DualMemoryGame';
import GoNoGoGame from '../pages/Elderly/Activities/games/GoNoGoGame';
import FindTheChangeGame from '../pages/Elderly/Activities/games/FindTheChangeGame';
import PeripheralAwarenessGame from '../pages/Elderly/Activities/games/PeripheralAwarenessGame';
import MemorySpanGame from '../pages/Elderly/Activities/games/MemorySpanGame';
import CulturalMemoryGame from '../pages/Elderly/Activities/games/CulturalMemoryGame';
import DailySequenceGame from '../pages/Elderly/Activities/games/DailySequenceGame';
import FaceNameMatchGame from '../pages/Elderly/Activities/games/FaceNameMatchGame';
import SoundMatchGame from '../pages/Elderly/Activities/games/SoundMatchGame';
import OddOneOutGame from '../pages/Elderly/Activities/games/OddOneOutGame';

export const GAME_REGISTRY: GameDefinition[] = [
  {
    id: 'memory_match',
    name: 'Memory Match',
    category: 'MEMORY',
    cognitiveDomains: ['memory'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: true,
    emoji: '🧩',
    description: 'Remember familiar objects',
    component: MemoryMatchGame,
  },
  {
    id: 'object_recognition',
    name: 'Object Recognition',
    category: 'MEMORY',
    cognitiveDomains: ['recognition'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: true,
    emoji: '👁️',
    description: 'Name what you see',
    component: ObjectRecognitionGame,
  },
  {
    id: 'attention',
    name: 'Attention',
    category: 'FOCUS',
    cognitiveDomains: ['attention'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 2,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: true,
    emoji: '🎯',
    description: 'Spot the right items',
    component: AttentionGame,
  },
  {
    id: 'pattern',
    name: 'Pattern Recognition',
    category: 'PATTERN',
    cognitiveDomains: ['pattern'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '🔷',
    description: 'What comes next?',
    component: PatternGame,
  },
  {
    id: 'routine_recall',
    name: 'Daily Routine Recall',
    category: 'ROUTINE',
    cognitiveDomains: ['routine'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: true,
    emoji: '📋',
    description: 'Order your morning',
    component: RoutineRecallGame,
  },
  {
    id: 'family_faces',
    name: 'Family & Faces',
    category: 'MEMORY',
    cognitiveDomains: ['memory'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: true,
    emoji: '👨‍👩‍👧',
    description: 'Recognize your loved ones',
    component: FamilyFacesGame,
  },
  {
    id: 'color_focus',
    name: 'Color Focus',
    category: 'FOCUS',
    cognitiveDomains: ['attention'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '🎨',
    description: 'Name the ink color, not the word',
    component: ColorFocusGame,
  },
  {
    id: 'quick_response',
    name: 'Quick Response',
    category: 'REACTION',
    cognitiveDomains: ['attention'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 2,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '⚡',
    description: 'Tap as soon as it turns green',
    component: QuickResponseGame,
  },
  {
    id: 'number_focus',
    name: 'Number Focus',
    category: 'FOCUS',
    cognitiveDomains: ['attention'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '🔢',
    description: 'Find the numbers in order',
    component: NumberFocusGame,
  },
  {
    id: 'block_memory',
    name: 'Block Memory',
    category: 'MEMORY',
    cognitiveDomains: ['memory'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '🟦',
    description: 'Watch and repeat the sequence',
    component: BlockMemoryGame,
  },
  {
    id: 'dual_memory',
    name: 'Dual Memory',
    category: 'ADVANCED',
    cognitiveDomains: ['memory', 'attention'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 5,
    elderlyFriendly: false,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '🧠',
    description: 'Does it match what you saw before?',
    component: DualMemoryGame,
  },
  {
    id: 'go_no_go',
    name: 'Gentle Focus',
    category: 'GENTLE',
    cognitiveDomains: ['attention'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 2,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '🟢',
    description: 'Tap green, wait on red',
    component: GoNoGoGame,
  },
  {
    id: 'find_the_change',
    name: 'Find the Change',
    category: 'PATTERN',
    cognitiveDomains: ['recognition'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 2,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: true,
    emoji: '🔍',
    description: 'Spot what changed',
    component: FindTheChangeGame,
  },
  {
    id: 'peripheral_awareness',
    name: 'Peripheral Awareness',
    category: 'ADVANCED',
    cognitiveDomains: ['attention'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 4,
    elderlyFriendly: false,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '👀',
    description: 'Spot what you saw, and where',
    component: PeripheralAwarenessGame,
  },
  {
    id: 'memory_span',
    name: 'Memory Span',
    category: 'MEMORY',
    cognitiveDomains: ['memory'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '📝',
    description: 'Remember a list of words',
    component: MemorySpanGame,
  },
  {
    id: 'cultural_memory',
    name: 'Procedural & Cultural Memory',
    category: 'CULTURAL',
    cognitiveDomains: ['recognition'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: true,
    emoji: '🎊',
    description: 'Recognize festivals and traditional items',
    component: CulturalMemoryGame,
  },
  {
    id: 'daily_sequence',
    name: 'Daily Sequence',
    category: 'ROUTINE',
    cognitiveDomains: ['routine'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '🗓️',
    description: 'Tap your daily routine, in order',
    component: DailySequenceGame,
    isNew: true,
  },
  {
    id: 'face_name_match',
    name: 'Face & Name Match',
    category: 'MEMORY',
    cognitiveDomains: ['recognition'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 3,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '🖼️',
    description: 'See a name, tap the matching face',
    component: FaceNameMatchGame,
    isNew: true,
  },
  {
    id: 'sound_match',
    name: 'Sound Match',
    category: 'GENTLE',
    cognitiveDomains: ['recognition'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 2,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '🔔',
    description: 'Listen, then tap the matching picture',
    component: SoundMatchGame,
    isNew: true,
  },
  {
    id: 'odd_one_out',
    name: 'Odd One Out',
    category: 'PATTERN',
    cognitiveDomains: ['pattern'],
    difficultyLevels: ['easy', 'medium', 'challenging'],
    estimatedDuration: 2,
    elderlyFriendly: true,
    voiceSupported: true,
    offlineSupported: true,
    culturalContentSupported: false,
    emoji: '🔎',
    description: 'Spot the one that does not belong',
    component: OddOneOutGame,
    isNew: true,
  },
];

export function getGameDefinition(id: string): GameDefinition | undefined {
  return GAME_REGISTRY.find((g) => g.id === id);
}
